import type { VolumeTurtleConfig } from "@/lib/config";

export const config: VolumeTurtleConfig = {
  balance: 10000,
  maxPositions: 5,
  riskPctPerTrade: 0.02,
  volumeSpikeMultiplier: 2.0,
  MOMENTUM_ENABLED: true,
  VOLUME_SPIKE_MIN: 2.0,
  BREAKOUT_MIN_CHG: 0.10,
  BREAKOUT_MIN_VOL: 3.0,
  SCORE_WEIGHT_REGIME: 0.35,
  SCORE_WEIGHT_BREAKOUT: 0.30,
  SCORE_WEIGHT_SECTOR: 0.25,
  SCORE_WEIGHT_LIQUIDITY: 0.10,
  TELEGRAM_BOT_TOKEN: "",
  TELEGRAM_CHAT_ID: "",
  rangePositionThreshold: 0.75,
  atrPeriod: 20,
  trailingStopDays: 10,
  hardStopAtrMultiple: 1.5,
  trailAtrMultiple: 2.0,
  scoreWeightRegime: 0.40,
  scoreWeightTrend: 0.30,
  scoreWeightVolume: 0.20,
  scoreWeightLiquidity: 0.10,
  cautionDrawdownPct: 10,
  pauseDrawdownPct: 20,
  quoteBatchSize: 10,
  quoteBatchDelayMs: 500,
  quoteLookbackDays: 60,
  dashboardPageSize: 20,
  dashboardLookbackDays: 14,
  lseScanHour: 17,
  lseScanMinute: 30,
  usScanHour: 22,
  usScanMinute: 0,
  syncDelayMs: 500,
};
